name: tilehuria
description: Mmap tile scraper and proxy
services:
  - package: "@platyplus/tilehuria"
  - package: "@platyplus/tilehuria-hasura"
  - package: "@platyplus/tilehuria-worker"
  - package: "@platyplus/tilehuria-hooks"
