{{- if .Values.digitalOceanToken -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  access-token: {{ .Values.digitalOceanToken | b64enc | quote }}
{{- end }}
