{{- $fullname := include "hasura-backend-plus.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  namespace: {​{​ .Release.Namespace }​}​
data:
{{- if .Values.auth.enabled }}
  jwt.expires.in: "{{ .Values.auth.jwt.expires.in | int }}"
  jwt.expires.refresh: "{{ .Values.auth.jwt.expires.refresh | int }}"
  jwt.customFields: "{{ join "," .Values.auth.jwt.customFields }}"
  {{- if not (or .Values.hasura.enabled .Values.connect.hasura.enabled) }}
  jwt.algorithm: "{{ .Values.auth.jwt.algorithm }}"
  jwt.claims.namespace: "{{ .Values.auth.jwt.claims.namespace }}"
  {{- end }}
{{- end }}
{{- if not (or .Values.hasura.enabled .Values.connect.hasura.enabled) }}
  hasura.endpoint: "{{.Values.hasura.endpoint }}"
{{- end }}
{{- if .Values.storage.enabled }}
  {{- if .Values.minio.enabled }}
  s3.bucket: {{ .Values.minio.defaultBuckets }}
  s3.endpoint: "http://{{ .Release.Name }}-minio:9000"
  s3.ssl: "true"
  {{- else }}
  s3.bucket: {{ .Values.storage.external.bucket }}
  s3.endpoint: {{ .Values.storage.external.endpoint }}
  s3.ssl: {{ .Values.storage.external.ssl }}
  {{- end }}
  {{- if .Values.storage.rules }}
  storage.rules: {{ .Values.storage.rules | toYaml | quote }}
  {{- end }}
{{- end }}
  emails.enabled: "{{ .Values.emails.enabled }}"
{{- if .Values.emails.enabled }}
  emails.smtp.host: "{{ .Values.emails.smtp.host }}"
  emails.smtp.port: "{{ .Values.emails.smtp.port | int }}"
  emails.smtp.secure: "{{ .Values.emails.smtp.secure }}"
  emails.smtp.user: "{{ .Values.emails.smtp.user }}"
  {{- if .Values.emails.sender }}
  emails.smtp.sender: "{{ .Values.emails.smtp.sender }}"
  {{- else }}
  emails.smtp.sender: "{{ .Values.emails.smtp.user }}"
  {{- end }}
  emails.smtp.auth-method: "{{ .Values.emails.smtp.authMethod }}"
{{- end }}
  limiter.max-requests: "{{ .Values.limiter.maxRequests | int }}"
  limiter.time-frame: "{{ .Values.limiter.timeFrame | int }}"